liTest run started
leTest scala.scalanative.junit.ExceptionBeforeClass failed: foo, took <TIME>
e2scala.scalanative.junit.ExceptionBeforeClass
liTest run finished: 1 failed, 0 ignored, 0 total, <TIME>
d
